/**
 * Re-export WASM bindings.
 *
 * These are generated by wasm-pack from pluresdb-wasm.
 * The actual binding file path depends on the build output.
 * During development, this is a placeholder that will be resolved
 * by the build system (vite plugin or direct wasm-pack output).
 */

// @ts-ignore — resolved at build time by vite-plugin-wasm or manual init
export {
  init,
  PluresDBBrowser,
  WasmCrdtStore,
  WasmAgensRuntime,
  WasmProcedureEngine,
  WasmChronosTimeline,
  pxCompile,
  pxParse,
  pxLint,
  pxExecute,
} from '@plures/pluresdb-wasm';
